config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new"  # /login will render sessions/new
  get "logout"=> "sessions#destroy"

  resources :users
  resources :photos
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :tags

end

app/models/add_photo_id_to_tags.rb
class AddPhotoIdToTags < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :photo
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/commenter.rb
class Commenter < User
	has_many :comments, as: :commentable
end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :comments, as: :commentable
  accepts_nested_attributes_for :comments


end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user

	has_many :comments, as: :commentable
	#has_many :comments

	#has_and_belongs_to_many :tags
	has_many :tags, as: :tagable

	mount_uploader :user_image, PhotoUploader
end

app/models/photos_tags.rb
class PhotosTags < ActiveRecord::Base
end

app/models/poster.rb
class Poster < User

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :photos
  belongs_to :taggable, polymorphic: true
  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :photos
	has_many :comments
	has_many :tags

	validates_presence_of :email
	validates_uniqueness_of :email
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :ensure_logged_in

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    if current_user.nil?
      redirect_to new_user_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@user_id = params.delete(:user_id)
		@commentable = find_commentable
		@comment = Comment.new(:user_id => @user_id, :commentable_id => @commentable_id, :commentable_type => @commentable.class.to_s)
		#@new_comment = Comment.new
		#@new_photo.comments.build # for nested form, builds new comment with image's id
	end

	def create
		@new_comment = Comment.new(comment_params)
		if @new_comment.save
			redirect_to :back
		else
			redirect_to photo_path(@new_comment.photo)
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def destroy
		@comment = Comment.find(params[:id])
		if @comment.destroy
			redirect_to comments_path
		else
			redirect_to comment_path
		end
	end

	def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      "Error updating comment"
    end
  end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :content, :commentable_type, :commentable_id, sessions_attributes: [:user_id])
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @new_event = Event.new
  end

  def create
    @new_event = Event.new(event_params)
    if @new_event.save
      redirect_to events_path
    else
      redirect_to new_event_path
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path
    else
      redirect_to edit_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_path
    else
      redirect_to edit_event_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :event_date, tags_attributes: [:name])
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.all
	end

	def new
		@new_photo = Photo.new
		#@new_photo.tags.build
		#@new_photo.comments.build # for nested form, builds new comment with image's id
	end

	def create
		@new_photo = Photo.new(photo_params)
		if @new_photo.save
			redirect_to photos_path
		else
			redirect_to new_photo_path
		end
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def show
		@photo = Photo.find(params[:id])
		#@photo.comments.build
		@new_comment = @photo.comments.build
		@photo.comments.build
		@new_comment.user = current_user
		# if @new_comment.save
		# 	redirect_to photo_path
		# else
		# 	redirect_to photos_path
		# end
		#@tags = @photo.tags
		#@tag = Tag.new
	end

	def destroy
		@photo = Photo.find(params[:id])
		if @photo.destroy
			redirect_to photos_path
		else
			redirect_to photo_path
		end
	end

	def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photos_path
    else
      "Error updating photo"
    end
  end

	def search
		@photos = Photo.search(params[:search])
	end

	def upload_user_image
		@photo = Photo.find(params[:id])
		file = @photo.uesr_image
		send_file file.path
	end

	def post_tag
		@new_tag = Tag.new
		@photo = Photo.find(params[:id])
	end

	def display_tag
		@photo = Photo.find(params[:id])
		@new_tag = @photo.tags.build
	end

	private

	def photo_params
		params.require(:photo).permit(:name, :description, :user_image, comments_attributes: [:user_id, :content], tags_attributes: [:photo_id, :name])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_filter :ensure_logged_in

  def new
  end

  def create
    user = User.find_by_email(params[:email]).try(:authenticate, params[:password])

    if user
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: "Logged in"
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "You've logged out!"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    # @new_tag = Tag.new(tag_params)

    # @taggable = find_taggable
    # @tag = Tag.new

    # @photo = @hoto.find(params[:id])
    # @tag = @photo.tags.new
    @tag = Tag.new
  end

def create
    @tag = Tag.where(name: params[:tag][:name]).first_or_create
    photo = Photo.find(params[:tag][:photo_id])
    photo.tags << @tag
    if @tag.save
      redirect_to photos_path
    else
      render new_tag_path
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end


  # def create
  #   @new_tag = Tag.new(tag_params)
  #   tag = Tag.where(name: tags_params[:name]).first_or_create
  #   if @photo.tags << tag
  #     redirect_to @current_photo, notice: "Comment created"
  #   else
  #     render :new
  #   end
  # end

  # def show
  #   @tag = Tag.find(params[:id])
  # end

  private 

  def tags_params
    params.require(:tag).permit(:name, :photo_id)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		@photos = Photo.all
	end

	def new
		@new_user = User.new
	end

	def create
		@new_user = User.new(user_params)
		if @new_user.save
			redirect_to users_path
		else
			redirect_to new_user_path
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path
		else
			redirect_to user_path
		end
	end

	def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      "Error updating user"
    end
  end

	def search
		@users = User.search(params[:search])
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
  	base_title = "SnapShot"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

	def formatted_date(date)
		date.strftime("%B %-d, %Y")
	end
end

app/views/comments/_form.html.haml
.container
	.col-md-12
		%h6.col.md-4
		= form_for [@commentable, @comment] do |f|
			= f.hidden_field :post_id
			%p
			= f.label :content, "New comment"
			%br
			= f.text_area :content, :rows => 4
			%p
			= f.submit "Post Comment"

app/views/comments/index.html.haml
- content_for(:title, 'Comments')

- @comments.each do |c| 
	.container
		.col-md-12
			%h6.col.md-4
			= link_to "#{c.user_id}", comment_path(c), method: :get
			%h4 #{c.comment}
			%br
			%br
			= button_to 'Edit Photo', edit_photo_path(photo), method: "get", :class => "btn btn-xs btn-warning"
			= button_to 'Delete Photo', photo, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete this photo?" }
			.col.md-8
			%br
			%br
			%br
= button_to 'Add Photo', new_photo_path, method: "get", :class => "btn btn-xs btn-warning"

app/views/events/_form.html.haml
= f.label :name
= f.text_field :name, class: "form-control"
%br
= f.label :description
= f.text_area :description, class: "form-control"
%br
= f.label :event_date
= f.date_field :event_date, class: "form-control"
%br
= f.submit type:'submit', class: "btn btn-default"
%br
%br

app/views/events/edit.html.haml
- content_for(:title, 'Edit Event')

.container
	.col-md-6
		%h1 Edit Event

		= form_for @event do |f|
			= render "form", f: f

app/views/events/index.html.haml
- content_for(:title, 'Events')

- @events.each do |event|
	.container
		.row
			.col-md-12
				.col-md-6
					%h5 Event Name:  #{event.name}
					%h5 Description:  #{event.description}
					= button_to 'Edit Event', edit_event_path(event), method: "get", :class => "btn btn-xs btn-success"
					= button_to 'Delete Event', event, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete?" }
					%br
					%br		
				.col-md-6
					%h3 My Comments

app/views/events/new.html.haml
- content_for(:title, 'Create A New Event')

.container
	.col-md-6
		%h1 New Event

		= form_for @new_event do |f|
			= render "form", f: f
			= f.fields_for :tags do |ff|
				Add a tag:
				= ff.text_field :name
			= f.submit
		%br

app/views/events/show.html.haml
- content_for(:title, '#{@event.name}')

.container
	.col-md-6
		%h1 Edit Event

		= form_for @event do |f|
			= render "form", f: f

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: "#"} SnapShot
    by KS
  %nav
    %ul
      %li= link_to "Add a photo", new_photo_path
      %li= link_to "Help", '#'

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse
	.navbar-inner
		.container
			%nav
				= image_tag "SnapShotbw.jpg"
				%ul.nav.navbar-nav.pull-right
					%li= link_to "Home",    '#'
					%li= link_to "Sign in", login_path
					%li= link_to "Sign up", logout_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
  %title= full_title(yield(:title))
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      %br
      - if current_user
        = link_to "Log Out", logout_path
      - else
        = link_to "Log In", login_path
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
    = yield
    = render 'layouts/footer'

app/views/photos/_form.html.haml
- @photos.each do |photo|
	.container
		.col-md-12
			%h6.col.md-4
			= link_to "#{photo.name}", photo_path(photo), method: :get
			%h4 #{photo.description}
			%br
			= image_tag photo.user_image.url
			%br
			%br
			= button_to 'Edit Photo', edit_photo_path(photo), method: "get", :class => "btn btn-xs btn-warning"
			= button_to 'Delete Photo', photo, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete this photo?" }
			.col.md-8
			%br
			%br
			%br
= button_to 'Add Photo', new_photo_path, method: "get", :class => "btn btn-xs btn-warning"

app/views/photos/_tagform.html.haml
= form_for @new_tag do |nt|
	= nt.label "Photo Tags"
	= nt.text_field :name
	= nt.hidden_field :photo_id, value: @photo.id
	= nt.submit "Tag Photo"
	%br
	%br
	Image Tags For This Photo:
	- @photo.tags.uniq.each do |tagname|
		= tagname.name

app/views/photos/edit.html.haml
= form_for @photo, url: photo_path do |f|
	= f.label :name
	= f.text_field :name
	%br
	= f.label :description
	= f.text_field :description
	%br
	Upload Image:
	= f.file_field :user_image
	%br
	= f.submit "Submit Changes"

app/views/photos/index.html.haml
- content_for(:title, 'Your Photos')

- @photos.each do |photo|
	.container
		.row
			.col-md-12
				= link_to "#{photo.name}", photo_path(photo), method: :get
				%p #{photo.description}
				%br
				= image_tag photo.user_image.url
				%br
				%br
				= button_to 'Edit Photo', edit_photo_path(photo), method: "get", :class => "btn btn-xs btn-sucess"
				= button_to 'Delete Photo', photo, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete this photo?" }
				%br
				%br
				%br
= button_to 'Add Photo', new_photo_path, method: "get", :class => "btn btn-xs btn-warning"

app/views/photos/new.html.haml
.container
	.col-md-12
		%h6.col.md-4
		= form_for @new_photo, url: photos_path do |f|
			= f.label :name
			= f.text_field :name
			%br
			= f.label :description
			= f.text_field :description
			%br
			Upload Image:
			= f.file_field :user_image
			%br
			= f.fields_for :tags do |f|
				Add A Tag:
				= f.text_field :name
			%br
			= f.submit "Add Photo"

app/views/photos/show.html.haml
- content_for(:title, 'Your Photo')
.container
	.row
		.col-md-12
		%h3= @photo.name
		%br
		Description:
		%h4= @photo.description
		%br
		= image_tag @photo.user_image.url, width: 550, height: 550
		%br
		= link_to "Edit Photo", edit_photo_path, :class => "btn btn-success"
		%br
		Tags:

		%br
	.row
		.col-md-12
		= form_for @new_tag do |nt|
			= nt.label "Photo Tags"
			= nt.text_field :name
			= nt.hidden_field :photo_id, value: @photo.id
			= nt.submit "Tag Photo"
			%br
			%br
		Image Tags For This Photo:
		- @photo.tags.uniq.each do |tagname|
			= tagname.name
	.row
		.col-md-12
		= form_for @new_comment, url: comments_path, method: :post do |f|
			= f.hidden_field :commentable_id, value: @photo.id
			= f.hidden_field :commentable_type, value: "Photo"
			= f.text_field :content
			= f.submit
		%br
		- @photo.comments.each do |c|
			%h4{ :style => "text-align:center" }= c.content
			%h4{ :style => "text-align:center" }= c.user_id

app/views/tags/index.html.haml
index.html.haml

app/views/tags/new.html.haml
new.html.haml

app/views/users/edit.html.haml
- content_for(:title, 'Update Profile')

.container
	%legend Update Your Profile
	= form_for @user, url: user_path do |f|
		= f.label :name
		= f.text_field :name
		%br
		= f.label :email
		= f.text_field :email
		%br
		Password:
		= f.password_field :password_digest
		%br
		= f.submit "Submit Changes"

app/views/users/index.html.haml
- content_for(:title, 'Your Profile')

- @users.each do |user|
	.container
		.row
			.col-md-12
				.col-md-6
					%h3 Profile for #{user.name}
					%h5 Name:  #{user.name}
					%h5 Email:  #{user.email}
					= button_to 'Edit Profile', edit_user_path(user), method: "get", :class => "btn btn-xs btn-success"
					= button_to 'Delete Profile', user, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete?" }
					%br
					%br		
				.col-md-6
					%h3 My Comments:
		.row
			.col-md-12
				%h3 My Photos
				= render :template => 'photos/index'
		%br

app/views/users/new.html.haml
- content_for(:title, 'Sign Up')

.container
	%legend Sign Up For An Account
	= form_for @new_user, url: users_path do |f|
		= f.label :name
		= f.text_field :name
		%br
		= f.label :email
		= f.text_field :email
		%br
		Password:
		= f.password_field :password
		Confirm Password:
		= f.password_field :password_confirmation
		%br
		= f.submit "Sign Up"

app/views/users/show.html.haml
- content_for(:title, 'Your Profile')

.container
	%legend 
		Profile for #{@user.name}
		.col-md-6
			%h4 Name:  #{@user.name}
			%h4 Email:  #{@user.email}
			= button_to 'Edit Profile', edit_user_path(@user), method: "get", :class => "btn btn-xs btn-success"
			= button_to 'Delete Profile', @user, method: "delete", :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure you want to delete?" }
			%br
			%br		
		.col-md-6
			%h3 My Comments:
			= link_to Comment.where(id: @user.id).pluck(:content).first, photo_path, method: "get"
	.row
		.col-md-12
			%h3 My Photos
			= link_to Photo.where(id: @user.id).pluck(:name).first, photo_path, method: "get"
			= button_to 'Add New Photo', new_photo_path, method: "get", :class => "btn btn-xs btn-success" 
			%br